[package]
name = "analytics"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
proto.workspace = true

tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
redis.workspace = true
deadpool-redis.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

thiserror = "2.0.18"
itertools = "0.15.0"

