[workspace]
members = ["analytics","common", "core", "gateway", "proto"]
resolver = "3"


[workspace.dependencies]
common = { path = "./common" }
proto = { path = "./proto" }

tonic = "0.14.6"
tokio = { version = "1.52.3", features = ["full"] }
axum = { version = "0.8.9" }
tower = { version = "0.5.3"}
redis = { version = "1.3.0", features = ["tokio-comp"] }
deadpool-redis = { version = "0.23.0" }
tracing = {version = "0.1.44"}
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
config = {version = "0.15", default-features = false, features = ["toml"]}
serde = { version = "1.0.228", features = ["derive"] }
