[redis]
host = "127.0.0.1"
port = 6379
ttl = 3600  # todo: is it used somewhere?

[database]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "postgres"
db_name = "kurlyk"

[gateway]
host = "127.0.0.1"
port = 3000

[core]
host = "127.0.0.1"
port = 3001

[analytics]
stream_name = "Events"  # TODO: should be in redis?
summary_interval_secs = 60
cleanup_interval_secs = 3600


[logging]
level = "info"