[redis]
host = "localhost"
#host = "redis"
port = 6379
cache_ttl_secs = 60

[redis.streams]
events = "Events"

[database]
host = "localhost"
#host = "db"
port = 5432
user = "postgres"
password = "postgres"
db_name = "kurlyk"

[gateway]
host = "localhost"
#host = "gateway"
port = 3000

[core]
host = "localhost"
#host = "core"
port = 3001

[analytics]
host = "localhost"
#host = "analytics"
port = 3002
read_batch_size = 100
read_block_millis = 250
flush_interval_secs = 10


[logging]
level = "info"
enabled = false
#otlp_endpoint = "http://alloy:4317"
otlp_endpoint = "http://localhost:4317"
