[package]
name = "proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tonic.workspace = true
#serde.workspace = true

prost = "0.14.4"
tonic-prost = "0.14.6"
#prost-types = { version = "0.14.4", features = ["chrono"] }
prost-wkt-types = "0.7.1"

[build-dependencies]
tonic-prost-build = "0.14.6"
protoc-bin-vendored = "3.2.0"