syntax = "proto3";
package core;

import "google/protobuf/empty.proto";

service LinkService {
  rpc CreateLink(CreateLinkRequest) returns (CreateLinkResponse);
  rpc GetLink(GetLinkRequest) returns (GetLinkResponse);
  rpc DeleteLink(DeleteLinkRequest) returns (google.protobuf.Empty);
}

message CreateLinkRequest {
  string short_code = 1; // todo: oneof with auto gen
  string target = 2;
}

message CreateLinkResponse {
  string short_code = 1;
}

message GetLinkRequest {
  string short_code = 1;
}

message GetLinkResponse {
  string target = 1;
}

message DeleteLinkRequest{
  string short_code = 1;
}